# Enable device power management and system poweroff
CONFIG_PM_DEVICE=y
CONFIG_POWEROFF=y

# Enable logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Enalble POSIX API for read-write locks
CONFIG_POSIX_API=y

# Enable console and RTT output
CONFIG_CONSOLE=y
CONFIG_RTT_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y

# Enable GPIO
CONFIG_GPIO=y

# Enable ADC
CONFIG_ADC=y
CONFIG_ADC_NRFX_SAADC=y

# Enable PWM
CONFIG_PWM=y

# Enable work queue for button processing
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8192

# Enable I2C
CONFIG_I2C=y

# Enable sensors drivers
CONFIG_SENSOR=y
CONFIG_TEMP_NRF5=y
CONFIG_OPT3001=y

# Enable clock control (required for temperature sensor)
CONFIG_CLOCK_CONTROL=y
CONFIG_CLOCK_CONTROL_NRF=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

# general bluetooth settings
CONFIG_BT=y
#CONFIG_BT_LOG_LEVEL_DBG=y
CONFIG_BT_MAX_CONN=1
CONFIG_BT_L2CAP_TX_BUF_COUNT=10
CONFIG_HEAP_MEM_POOL_SIZE=8192

# Bluetooth Low Energy Peripheral (Slave Mode)
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="Bike LED"

# Bluetooth Low Energy Central (Master Mode)
#CONFIG_BT_CENTRAL=y
#CONFIG_BT_GATT_CLIENT=y
#CONFIG_EVENTS=y
#CONFIG_LOG_BUFFER_SIZE=4096
#CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=2048
#CONFIG_BT_BUF_ACL_RX_SIZE=251
#CONFIG_BT_BUF_ACL_TX_SIZE=251
#CONFIG_BT_BUF_ACL_TX_COUNT=10

