# Enable device power management and system poweroff
CONFIG_PM_DEVICE=y
CONFIG_POWEROFF=y

# Enable logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_MODE_IMMEDIATE=y

# Debug/fault diagnostics
CONFIG_ASSERT=y
CONFIG_FAULT_DUMP=2
CONFIG_THREAD_NAME=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_STACK_SENTINEL=y
CONFIG_INIT_STACKS=y

# Enalble POSIX API for read-write locks
CONFIG_POSIX_API=y

# Enable console and RTT output
CONFIG_CONSOLE=y
CONFIG_RTT_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y

# Enable GPIO
CONFIG_GPIO=y

# Enable ADC
CONFIG_ADC=y
CONFIG_ADC_NRFX_SAADC=y

# Enable PWM
CONFIG_PWM=y

# Enable work queue for button processing
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# Enable I2C
CONFIG_I2C=y

# Enable sensors drivers
CONFIG_SENSOR=y
CONFIG_TEMP_NRF5=y
CONFIG_OPT3001=y

# Enable clock control (required for temperature sensor)
CONFIG_CLOCK_CONTROL=y
CONFIG_CLOCK_CONTROL_NRF=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

# bluetooth settings
CONFIG_BT=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_OBSERVER=y
CONFIG_BT_SMP=y
CONFIG_BT_GATT_CLIENT=y

CONFIG_BT_BUF_ACL_RX_SIZE=255
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_BUF_CMD_TX_SIZE=255
CONFIG_BT_BUF_EVT_DISCARDABLE_SIZE=255

CONFIG_BT_L2CAP_TX_MTU=247